CREATE DATABASE SALESDATADB;
USE SALESDATADB;
CREATE TABLE SALES(
SALE_ID INT PRIMARY KEY,
PRODUCT VARCHAR(50),
CATEGORY VARCHAR(50),
date DATE,
Quantity INT,
PRICE DECIMAL(10,2),
REVEUNE DECIMAL(10,2)
);

INSERT INTO SALES (SALE_ID,PRODUCT,CATEGORY,DATE,QUANTITY,PRICE,REVEUNE)
VALUES
(1,"LAPTOP","ELECTRONICS","2024-08-16",2,500,1000),
(2,"PHONE","ELECTRONICS","2024-08-15",3,300,900),
(3,"SHOES","APPAREL","2024-08-14",5,50,550);

SELECT SUM(REVEUNE) AS TOTAL_REVEUNE FROM SALES;

SELECT category,SUM(REVEUNE) AS CATEGORY_REVEUNE
FROM sales
GROUP BY CATEGORY
ORDER BY CATEGORY_REVEUNE DESC;

SELECT month(DATE) AS SALE_MONTH , SUM(REVEUNE) AS MONTHLY_REVEUNE
FROM SALES
GROUP BY SALE_MONTH
ORDER BY SALE_MONTH ;



SELECT * FROM SALES;

